# Generated by Django 3.1.9 on 2021-05-05 16:20

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailimages", "0022_uploadedimage"),
        ("wagtailcore", "0052_pagelogentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category page",
                "verbose_name_plural": "Category pages",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="SectionPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Section page",
                "verbose_name_plural": "Section pages",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ArticlePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "content",
                    wagtail.core.fields.RichTextField(
                        null=True, verbose_name="article content"
                    ),
                ),
                (
                    "article_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="article image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article page",
                "verbose_name_plural": "Article pages",
            },
            bases=("wagtailcore.page",),
        ),
    ]
